### ISSUE TITLE
메뉴출력에 관련하여 아이디어 (한국어 -> 영어)

### ISSUE THREAD

**Issue by SoejeongWoo** [2023OSSL-YE-SJ/team_miniproject#14]
한국어로 menu.txt를 저장하였을때는 마지막에 메뉴를 출력할때 지저분하게 출력이 되는데 영어로 메뉴를 바꾸면 정갈하게 출려이 되어서 어느 menu.txt를  한국어로 하고 싶으신지 영어로 하고 싶으신지 여쭤보고 싶습니다. 

아래 사진은 영어버전일 때 출력되어 나오는 결과입니다. 
![image](https://github.com/2023OSSL-YE-SJ/team_miniproject/assets/131163879/a9dbf843-2c62-4bb4-90d7-6f4dcf845b6d)

**Comment by yeeun66** [comment]
영어로 하는 거 좋은 것 같아요 !! 
혹시 영어로 코드랑 메뉴 파일 수정 가능하신가요?

**Comment by SoejeongWoo** [comment]
넵 가능합니다!! 오전중으로 완성해서 올려두겠습니다!:)
