### ISSUE TITLE
idea for the miniproject

### ISSUE THREAD

**Issue by SoejeongWoo** [2023OSSL-YE-SJ/team_miniproject#3]
1. Main idea: 다이어트 식당
2. 종류: 셀러드, 라이스류, 면류, 빵, 음료 (선택할 수 있는 함수)
3. - 1. 메뉴선택/2. 칼로리 세분화
4. - 그 밑에 세분화 해서 메뉴를 선택할 수 있는 함수를 만든다. (칼로리 설정)

**Comment by yeeun66** [comment]
typedef struct {    
    char name[100]; // 이름
    int price; // 가격
    double calorie; // 칼로리
    }Product;
    // 구조체 
    
int createProduct(Product *p); // 제품을 추가하는 함수 => 메뉴 선택
void readProduct(Product *p); // 하나의 제품 출력 함수 => 구매 목록 보기
int updateProduct(Product *p); // 제품을 수정하는 함수 => 구매 목록 수정 
int deleteProduct(Product *p); // 제품을 삭제하는 함수 => 구매 취소 [환불]

void saveProduct(Product *p, int count); //데이터를 파일에 저장 하는 함수
int loadProduct(Product *p);// 저장된 데이터를 불러오는 함수

int selectMenu(); // 데이터를 다룰 때, 원하는 메뉴를 선택하는 함수 -> crud 등 기능 선택
int selectCalorie(); // 데이터를 다룰 때, 원하는 메뉴를 구체적으로 선택하는 함수

int listProduct(Product *p, int count); // 제품 리스트 출력

void searchProductType(Product *p, int count); // 메뉴 종류 검색
void searchProductCalories(Product *p, int count); // 칼로리 검색
