### ISSUE TITLE
CRUD, Main함수, 파일 관련 함수 구현

### ISSUE THREAD

**Issue by yeeun66** [2023OSSL-YE-SJ/team_miniproject#6]
CRUD, Main 함수, 파일 관련 함수 구현해서 올려 놓았습니다. 수정된 사항이 조금 있으니 잘 확인해서 나머지 코드 작성해주세요!

**Comment by yeeun66** [comment]
void searchProductTypeAndCalories(Product *p[], int count);  함수는 메뉴종류랑 칼로리 한 함수에서 검색할 수 있게 만든 함수이고, 이거 구현하면 됩니다. 그리고 int loadProduct(Product **p) 이 함수가 약간 문제가 있어서 코드 보고 같이 수정해주시면 감사하겠습니다 :)

**Comment by SoejeongWoo** [comment]
[ int loadProduct(Product **p) 이 함수가 약간 문제가 있어서 코드 보고 같이 수정해주시면 감사하겠습니다 :) ]
이 부분에서 약간의 문제가 뭔지 알려주시면 감사하겠습니다!!
